services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "8e"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
      DISK_SIZE: "256G"
      DISK2_SIZE: "32G"
      DISK3_SIZE: "64G"
      ARGUMENTS: "-device usb-audio"
      ARGUMENTS: "-device ich9-intel-hda -device hda-output"
volumes:
  - ./example2:/storage2
  - ./example3:/storage3
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: on-failure
    stop_grace_period: 720m
